### ISSUE TITLE
/usr/bin/openssl not found error after your last commit

### ISSUE THREAD

**Issue by joozyz** [zypr/perfectrootserver#1]
cp libcrypto.pc /usr/local/ssl/lib/pkgconfig
chmod 644 /usr/local/ssl/lib/pkgconfig/libcrypto.pc
cp libssl.pc /usr/local/ssl/lib/pkgconfig
chmod 644 /usr/local/ssl/lib/pkgconfig/libssl.pc
cp openssl.pc /usr/local/ssl/lib/pkgconfig
chmod 644 /usr/local/ssl/lib/pkgconfig/openssl.pc
mv: cannot stat `/usr/bin/openssl': No such file or directory
root@srv:~# cd /usr/bin/openssl
bash: cd: /usr/bin/openssl: No such file or directory

**Comment by zypr** [comment]
thanks.. nobody can move a non existing file.

b89f7b64d99efa5dd1fb0e8cf671dd53b409c911

**Comment by joozyz** [comment]
i know that but that was the output of the script...

**Comment by zypr** [comment]
It was meant to be ironic, because it was my fault. :+1:

**Comment by joozyz** [comment]
sry my fault :(
