### ISSUE TITLE
Script doesn't update bash correctly. End up in 404 and stops

### ISSUE THREAD

**Issue by AndreasKnight** [zypr/perfectrootserver#3]
![root_mai10_1431268943](https://cloud.githubusercontent.com/assets/12384581/7555923/8c59aad0-f75c-11e4-8ee8-420ad14a1cfa.png)
Script is updating until 033
try to get 034 (doesn't exist) and end up with an 404 Error. Script stops here. 

If you start the script again you get the same error.

**Comment by zypr** [comment]
fixed 7e6dc78baee972ba052b90aeb84aa94918c0ad00
