### ISSUE TITLE
The current Nginx Version is not compatible with the acutal Installation-Script

### ISSUE THREAD

**Issue by MisterChoc** [zypr/perfectrootserver#5]
The needed folders like "sides-enables" and "sides-available" are not available in the new nginx version. The installation script failed after linking the webserver sides.

**Comment by shoujii** [comment]
A clean installation with the following versions is working flawless for me:
NGINX_VERSION="1.11.3"
OPENSSL_VERSION="1.0.2h"
OPENSSH_VERSION="7.3p1"
NPS_VERSION="1.11.33.2"

I used my fork for this test, but the nginx stuff is untouched, so it should work here too
