### ISSUE TITLE
Script not installing 

### ISSUE THREAD

**Issue by doeman20** [zypr/perfectrootserver#6]
Please i learned that many linux users are using simple server and this simple server can not make some attack works fine that we need need root server to make attack works better but i think this Perfect root server will make things work fine for me 
Please help me brothers ,,,, i need pure guideline to install the latest Root server on Kali linux 2016 2 
PLease help am using Kali linux 2016.2 ,,, i got this result  when i try to install perfect root server latest release
Rolling.... Error Response  .... Thanks in Advance Brothers 
bash ~/install.sh
ends up in .....
bash: /root/install.sh: No such file or directory

**Comment by doeman20** [comment]
![screenshot from 2016-11-23 23-47-51](https://cloud.githubusercontent.com/assets/16491995/20589531/5f487f9e-b21d-11e6-9177-70f1fb1521ce.png)

**Comment by zypr** [comment]
hi there, i stopped developing this script. please try the fork from shoujii -> https://github.com/shoujii/perfectrootserver

**Comment by doeman20** [comment]
Thank you brother but i prefer you're the best........
