### ISSUE TITLE
Certificate not found

### ISSUE THREAD

**Issue by antreos** [zypr/perfectrootserver#8]
Hi,
done the install two times. Got both times: sources/script/functions.sh: line 627: /etc/nginx/ssl/knightmail.pro.pem: No such file or directory
unable to load Public Key

How can I fix this?

**Comment by BoBBer446** [comment]
Why you post on Zyprs Repo?
You know, that Zypr does not support this script anymore...You know it.
I know, that you know it becaus you post an issue on the fork: https://github.com/shoujii/perfectrootserver/issues/12

The script from Zypr is not up-to-date! Please use the latest version from here:
Https://github.com/shoujii/perfectrootserver

Currently, you can also test the beta, coming soon version 1.0

**Comment by antreos** [comment]
Hi @BoBBer446 
posted this issue before I found out that it isn't supported. (see time stamps this is around 1 day earlier then the issue on https://github.com/shoujii/perfectrootserver
:)
